version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/Tallinn
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: components/jquery
    versions:
    - "> 1.8.3"
  - dependency-name: components/jqueryui
    versions:
    - "> 1.11.4"
