language: php
sudo: false

addons:
  apt:
    packages:
    # install all locales used by eventum
    - language-pack-br
    - language-pack-ca
    - language-pack-cs
    - language-pack-da
    - language-pack-de
    - language-pack-eo
    - language-pack-es
    - language-pack-et
    - language-pack-fi
    - language-pack-fo
    - language-pack-fr
    - language-pack-he
    - language-pack-ht
    - language-pack-hu
    - language-pack-id
    - language-pack-it
    - language-pack-ja
    - language-pack-ko
    - language-pack-lt
    - language-pack-lv
    - language-pack-nl
    - language-pack-oc
    - language-pack-pl
    - language-pack-pt
    - language-pack-ru
    - language-pack-si
    - language-pack-sv
    - language-pack-ta
    - language-pack-th
    - language-pack-tr
    - language-pack-uk
    - language-pack-ur
    - language-pack-vi
    - language-pack-zh-hans

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

before_install:
  # display some info from system
  - dpkg --list | grep language-pack
  - echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - locale -a
  - make php-cs-fixer.phar
  # pull translations from launchpad
  - bzr branch lp:~glen666/eventum/po po
  - cp -af po/localization/*.po localization

install:
  - composer install --no-interaction --prefer-source
  - make pear-fix

notifications:
  irc:
    channels: "chat.freenode.net#eventum"
    skip_join: true

script:
  - phpunit -v --debug

# vim:ts=2:sw=2:et
