language: php
sudo: required
dist: trusty

# disable the default submodule logic
git:
  submodules: false

jobs:
  # NOTE: when adding/removing jobs, update bin/ci/snapshot.sh travis_log job_id
  allow_failures:
    - php: "7.2"
    - php: "nightly"
  include:
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "nightly"

    - php: "7.1"
      services:
        - mysql
      env:
        - MIGRATIONS=1
      script: |
        mysql -e 'CREATE DATABASE IF NOT EXISTS e_test'
        cp -p tests/travis/*.php config
        php bin/upgrade.php

    # TODO: would be nice to have two separate stages, one for build, and other for actually publishing
    - stage: GitHub Release
      php: "7.1"
      script:
        - bin/ci/dist.sh

      # https://docs.travis-ci.com/user/deployment/releases
      # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
      before_deploy:
        - bin/ci/changelog.sh

      deploy:
        provider: releases
        # Create token in https://github.com/settings/tokens and set as env var:
        # $ travis env set -p GITHUB_API_TOKEN ...
        # or via https://travis-ci.org/eventum/eventum/settings
        api_key: $GITHUB_API_TOKEN
        file_glob: true
        file:
          - eventum-*.tar.xz
        skip_cleanup: true
        overwrite: true
        on:
          repo: eventum/eventum
          tags: true

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor
    - cache
    - vendor

before_install:
  - bin/ci/configure.sh
  - cp config/setup.phpunit.php config/setup.php

install:
  - composer install --no-interaction --prefer-dist

script:
  - PATH=$HOME/.composer/vendor/bin:$PATH
  - phpunit --verbose --exclude-group ldap,imap,logger,mail,api,locale,date,db,crypto

notifications:
  irc:
    channels: "chat.freenode.net#eventum"
    skip_join: true

# vim:ts=2:sw=2:et
