root:
    path: /
    controller: Eventum\Controller\IndexController::defaultAction

index:
    path: /index.php
    controller: Eventum\Controller\IndexController::defaultAction

confirm:
    path: /confirm.php
    methods: GET
    controller: Eventum\Controller\ConfirmController::defaultAction

scm_ping:
    path: /scm_ping.php
    methods: POST
    controller: Eventum\Controller\ScmPingController::defaultAction

searchbar:
    path: /searchbar.php
    methods: GET
    controller: Eventum\Controller\SearchbarController::defaultAction

forgot_password:
    path: /forgot_password.php
    methods: GET|POST
    controller: Eventum\Controller\ForgotPasswordController::defaultAction

login:
    path: /login.php
    controller: Eventum\Controller\SecurityController::login

logout:
    path: /logout.php
    methods: GET
    # NB: controller is not needed

select_project:
    path: /select_project.php
    methods: GET|POST
    controller: Eventum\Controller\SelectProjectController::indexAction

setup:
    path: /setup
    methods: GET|POST
    controller: Eventum\Controller\Setup\SetupController::defaultAction

front:
    path: /front
    controller: Eventum\Controller\FrontController::indexAction

ajax_dynamic_custom_field.js:
  path: /ajax/dynamic_custom_field.js.php
  controller: Eventum\Controller\Ajax\DynamicCustomFieldController::indexAction

ajax_get_custom_field_dynamic_options:
  path: /ajax/get_custom_field_dynamic_options.php
  controller: Eventum\Controller\Ajax\DynamicCustomFieldOptionsController::indexAction

ajax_update:
  path: /ajax/update.php
  controller: Eventum\Controller\Ajax\UpdateController::indexAction

ajax_upload:
  path: /ajax/upload.php
  controller: Eventum\Controller\Ajax\UploadController::indexAction

# vim:ts=2:sw=2:et
